version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: shop_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=shop
      - POSTGRES_PASSWORD=shop
      - POSTGRES_DB=shop
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shop -d shop"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db-data:
